#version: '3.9'

services:
  webapp:
    build:
      context: ./webapp-static  # Build from the nginx/ directory
    container_name: html-nginx-static
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
      - "8090:8090"  # Map port 8090 on the host to port 8090 in the container
  
  apibackend:
    build:
      context: ./web-api  # Build from the php/ directory
    container_name: php-webserver
    ports:
      - "8081:80"  # Map port 8081 on the host to port 80 in the container

